.hykkt_script_template:
 script:
    - |
      set -xv
      export WORKDIR="$HOME/gitlab/$CI_JOB_ID"
      if [[ ! -d "$WORKDIR" ]]; then
        mkdir -p "$WORKDIR"
        cp -R ./* "$WORKDIR"
      fi
      cd $WORKDIR
      [ -f output ] && rm output
      touch output
      tail -f output &
      tailpid=$!
      sinfo -l | grep $SLURM_Q

      #test build script
      jobid=$(sbatch --export=ALL -A EXASGD --gres=gpu:1 --ntasks=1 -p $SLURM_Q -o output -e output -t 60:00 $WORKDIR/buildsystem/build.sh $SCRIPT_ARGS)
      export jobid=$(echo $jobid | cut -f4 -d' ')
      echo $jobid > "$WORKDIR/jobid"
      res=1
      while :;
      do
        if [[ "$(awk 'BEGIN{i=0}/BUILD_STATUS/{i++}END{print i}' output)" != "0" ]]; then
          kill $tailpid
          echo 'Last tail of build output:'
          tail -n 200 output
          res=$(grep BUILD_STATUS output | tail -n 1 | cut -f2 -d':')
          break
        fi
        sleep 30
      done
      rm "$WORKDIR/jobid"
      echo "Finished job with code $res"
      exit $res


.pnnl_tags_template:
  tags:
    - k8s
    - ikp
    - exasgd
    - marianas

.pnnl-rules:
  rules:
   - if: '$CI_PROJECT_ROOT_NAMESPACE == "exasgd"' # Will only apply to PNNL

.pnnl-nonhpc-tags:
  tags:
    - k8s
".gitlab-ci.yml" 148L, 3510C


hykkt-test-deception:
  stage: test
  needs: []
  variables:
    SLURM_Q: "a100_shared"
    MY_CLUSTER: "deception"
    OUTPUT_SUFFIX: "_build"
    SCRIPT_ARGS: " --build-only --job=gcc-cuda "
    WORKDIR_SUFFIX: "x86_64-gcc-cuda-build"
  extends:
    - .pnnl-rules
    - .pnnl_tags_template
    - .hykkt_script_template

hykkt-test-newell:
  stage: test
  needs: []
  variables:
    SLURM_Q: "newell_shared"
    MY_CLUSTER: "newell"
    OUTPUT_SUFFIX: "_test"
    SCRIPT_ARGS: " --test-only --job=gcc-cuda "
    WORKDIR_SUFFIX: "ppc64le-gcc-cuda-build"
  extends:
  - .pnnl-rules
  - .pnnl_tags_template
  - .hykkt_script_template

.report-status:
  variables:
  GIT_STRATEGY: none
  tags:
    - basic
  extends:
    - .pnnl_rules
    - pnnl_environment_template
  script:
    - curl -X POST -H @${GITHUB_CURL_HEADERS} https://api.github.com/repos/${STATUS_PROJECT}/statuses/${CI_COMMIT_SHA}?state=${CI_JOB_NAME}\&context=${STATUS_NAME}\&target_url=${CI_PIPELINE_URL}
  environment:
      name: reporting-gitlab
pending:
  extends:
    - .report-status
  stage: .pre

success:
  extends:
    - .report-status
  stage: .post
