trigger_deception:
 trigger:
   include:
      - local: .gitlab/deception.gitlab-ci.yml
      - local: .gitlab/basic.gitlab-ci.yml
   

trigger_newell:
  trigger:
    include:
      - local: .gitlab/newell.gitlab-ci.yml
      - local: .gitlab/basic.gitlab-ci.yml
