#!/bin/sh
#SBATCH -A exasgd
#SBATCH -p a100_shared
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 00:59:00
#SBATCH --gres=gpu:1
module load cmake/3.15.3
module load gcc/7.5.0
module load cuda/11.1
srun ./run_Ruiz 




