#!/bin/bash

source ~/deception_vars.sh
nvcc -ccbin=gcc -Xcompiler -g -G -gencode arch=compute_80,code=sm_80 -DCUDA11 \
  -o run_Ruiz -lcusparse -lcusolver -lcublas -lrt -lgfortran Ruiz_driver.cu && \
  sbatch Ruiz_batch
