# CMake generated Testfile for 
# Source directory: /home/shakedregev/hykkt/examples
# Build directory: /home/shakedregev/hykkt/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(permutation "cuda-memcheck" "/home/shakedregev/hykkt/examples/perm_driver")
set_tests_properties(permutation PROPERTIES  _BACKTRACE_TRIPLES "/home/shakedregev/hykkt/examples/CMakeLists.txt;96;add_test;/home/shakedregev/hykkt/examples/CMakeLists.txt;0;")
add_test(ruiz_scaling_test "cuda-memcheck" "/home/shakedregev/hykkt/examples/ruiz_driver")
set_tests_properties(ruiz_scaling_test PROPERTIES  _BACKTRACE_TRIPLES "/home/shakedregev/hykkt/examples/CMakeLists.txt;102;add_test;/home/shakedregev/hykkt/examples/CMakeLists.txt;0;")
add_test(cholesky "cuda-memcheck" "/home/shakedregev/hykkt/examples/chol_driver" "/home/shakedregev/hykkt/src/mats/a200_chol//H_matrix_ACTIVSg200_AC_00.mtx" "/home/shakedregev/hykkt/src/mats/a200_chol//rhs_chol_ACTIVSg200_AC_00.mtx")
set_tests_properties(cholesky PROPERTIES  _BACKTRACE_TRIPLES "/home/shakedregev/hykkt/examples/CMakeLists.txt;107;add_test;/home/shakedregev/hykkt/examples/CMakeLists.txt;0;")
add_test(schur_cg "cuda-memcheck" "/home/shakedregev/hykkt/examples/schur_cg_driver" "/home/shakedregev/hykkt/src/mats/a200_schur//JC_matrix_ACTIVSg200_AC_00.mtx" "/home/shakedregev/hykkt/src/mats/a200_schur//H_matrix_ACTIVSg200_AC_00.mtx" "/home/shakedregev/hykkt/src/mats/a200_schur//CG_rhs_ACTIVSg200_AC_00.mtx")
set_tests_properties(schur_cg PROPERTIES  _BACKTRACE_TRIPLES "/home/shakedregev/hykkt/examples/CMakeLists.txt;112;add_test;/home/shakedregev/hykkt/examples/CMakeLists.txt;0;")
add_test(hybrid1 "cuda-memcheck" "/home/shakedregev/hykkt/examples/hybrid_driver" "/home/shakedregev/hykkt/src/mats/a200//block_H_matrix_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_Dd_matrix_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_J_matrix_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_Jd_matrix_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_rx_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_rs_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_ry_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_ryd_ACTIVSg200_AC_10.mtx" "2" "10000.0")
set_tests_properties(hybrid1 PROPERTIES  _BACKTRACE_TRIPLES "/home/shakedregev/hykkt/examples/CMakeLists.txt;117;add_test;/home/shakedregev/hykkt/examples/CMakeLists.txt;0;")
add_test(hybrid2 "cuda-memcheck" "/home/shakedregev/hykkt/examples/hybrid_driver" "/home/shakedregev/hykkt/src/mats/a2000//block_H_matrix_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_Dd_matrix_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_J_matrix_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_Jd_matrix_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_rx_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_rs_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_ry_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_ryd_ACTIVSg2000_AC_09.mtx" "3" "10000.0")
set_tests_properties(hybrid2 PROPERTIES  _BACKTRACE_TRIPLES "/home/shakedregev/hykkt/examples/CMakeLists.txt;119;add_test;/home/shakedregev/hykkt/examples/CMakeLists.txt;0;")
add_test(solver1 "cuda-memcheck" "/home/shakedregev/hykkt/examples/solver_driver" "/home/shakedregev/hykkt/src/mats/a200//block_H_matrix_ACTIVSg200_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_Dd_matrix_ACTIVSg200_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_J_matrix_ACTIVSg200_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_Jd_matrix_ACTIVSg200_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_rx_ACTIVSg200_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_rs_ACTIVSg200_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_ry_ACTIVSg200_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_ryd_ACTIVSg200_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_H_matrix_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_Dd_matrix_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_J_matrix_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_Jd_matrix_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_rx_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_rs_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_ry_ACTIVSg200_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a200//block_ryd_ACTIVSg200_AC_10.mtx" "2" "10000.0")
set_tests_properties(solver1 PROPERTIES  _BACKTRACE_TRIPLES "/home/shakedregev/hykkt/examples/CMakeLists.txt;124;add_test;/home/shakedregev/hykkt/examples/CMakeLists.txt;0;")
add_test(solver2 "cuda-memcheck" "/home/shakedregev/hykkt/examples/solver_driver" "/home/shakedregev/hykkt/src/mats/a2000//block_H_matrix_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_Dd_matrix_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_J_matrix_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_Jd_matrix_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_rx_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_rs_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_ry_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_ryd_ACTIVSg2000_AC_09.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_H_matrix_ACTIVSg2000_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_Dd_matrix_ACTIVSg2000_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_J_matrix_ACTIVSg2000_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_Jd_matrix_ACTIVSg2000_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_rx_ACTIVSg2000_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_rs_ACTIVSg2000_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_ry_ACTIVSg2000_AC_10.mtx" "/home/shakedregev/hykkt/src/mats/a2000//block_ryd_ACTIVSg2000_AC_10.mtx" "3" "10000.0")
set_tests_properties(solver2 PROPERTIES  _BACKTRACE_TRIPLES "/home/shakedregev/hykkt/examples/CMakeLists.txt;126;add_test;/home/shakedregev/hykkt/examples/CMakeLists.txt;0;")
