#!/bin/bash

source ~/deception_vars.sh
if [ $1 = "test1" ]
then
  runfile="hybrid_batch_200"
fi
if [ $1 = "test2" ]
then
  runfile="hybrid_batch_2000"
fi
nvcc -ccbin=gcc -Xcompiler -g -G -gencode arch=compute_80,code=sm_80 -DCUDA11 -o hybrid_solver -lcusparse -lcusolver -lcublas -lrt -lgfortran cuSolver_driver_hybrid.cu && \
  sbatch $runfile
